general.import = ["/Users/neevek/.config/alacritty/alacritty-theme/themes/hyper.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#000000"
foreground = "#88ff88"

[font]
builtin_box_drawing = true
size = 14

[font.normal]
# family = "Lekton Nerd Font Mono"
family = "M+1Code Nerd Font"
# family = "ProggyClean CE Nerd Font Mono"

[font.bold]
family = "M+1Code Nerd Font"

[font.italic]
family = "M+1Code Nerd Font"
style = "Italic"

[scrolling]
history = 50000

[window]
startup_mode = "Maximized"
